### ISSUE TITLE
Foldable comments

### ISSUE THREAD

**Issue by Splines** [bhoov/vscode-manim#1]
Thanks for the quick creation of this extension ;) Will give it a try in the next few days.

In the video [How I animate 3Blue1Brown](https://youtu.be/rbu7Zu5X1zI), you see at [5:29](https://youtu.be/rbu7Zu5X1zI?t=329) how comments are foldable in Sublime due to [these lines of code](https://github.com/3b1b/videos/blob/bfa09d02afa9b802004525a86592162021afede9/sublime_custom_commands/manim_plugins.py#L193-L229). It'd be awesome to have something similar for VSCode. Additionally, I'd even prefer a special comment syntax, such that not every comment is foldable, e.g. only comments that start with a customizable string, for exampel `#!` or `# ==` or whatever. This could maybe be a user-adjustable parameter for the extension with a sensible default value.

**Comment by VladimirFokow** [comment]
for info: currently, this can be done in VSCode in python like this:  
https://stackoverflow.com/a/60442670

```py
#region <REGION NAME>

# any code goes here, including multiple comment lines

#endregion
```

**Comment by Splines** [comment]
> for info: currently, here is what's possible in VSCode in python:
https://stackoverflow.com/a/60442670

Thanks for pointing that out. I hope there's another option as I'd hate to have to include an ending comment like `#endregion`. A starting comment should be enough in my opinion. Hopefully, this is somehow feasible within the VSCode extension framework.

**Comment by bhoov** [comment]
This is a really neat feature. I actually think his workflow could be improved by taking advantage of the "pypercent" format, i.e, using special code cells in python

```
#%% CODE CELL

#some code...

#%%NEXT CODE CELL
```

Folding these regions is also supported through the Jupyter extension, I believe. And we wouldn't need to highlight the code every time, we could just run that cell

**Comment by Splines** [comment]
Oh yeah true, there exists these [Jupyter cells](https://code.visualstudio.com/docs/python/jupyter-support-py#_jupyter-code-cells) in normal python files as well, that's cool. I wouldn't like to work in a separate jupyter notebook (`.ipynb`) for this, but this just feels like the right mix: have my plain-old Python file and then sprinkle in some comments to get executable cells. And this would even be more comfortable with in-line code-lense to execute a cell.

This execution of the cell would however be different from the Jupyter extension. I mean, the Jupyter extension would just take the code in the cell and execute it in a Python REPL. But what we want is different behavior (copy to clipboard, paste `clipboard_paste()` into terminal etc.).

However: if the Jupyter extension is able to define such foldable cold regions based on custom comments, than in principle every extension can, even this one 👍 (Of course how much effort that is going to be is another question).

**Comment by bhoov** [comment]
I propose:

- `vscode.CheckpointPasteCell` command that:
    1. uses regex to extract the text between the preceding cell delimiter `#%%` and the next (or EOF if no subsequent `#%%` is found)
    2. If there is no title for the cell e.g., `#%% SECTION TITLE`, look in the following line for a normal comment and use this as a section title. If no section title or comment is present, run `checkpoint_paste` without the scene checkpointing functionality, raising a warning appropriately
- no-op if no `#%%` cell delimiter precedes the current cursor

I would hope to keep this functionality decoupled from the jupyter behavior, but I see how the presence of "run cell | run below | debug cell" can be confusing since it will not run in manim but instead use a different ipython kernel. 

How could we make this more usable? I see several options, none perfect:
1. (idk how to but) Hide these buttons presented by the jupyter extension if the file contains the text `from manimlib import *`
2. (idk how to but) If file contains text `from manimlib import *`, hijack the `run cell` button to send to the manimgl interactive ipython. We probably want to hide the `debug cell` and `run below` appropriately

**Comment by VladimirFokow** [comment]
1. The fastest solution I see to make it "more usable" is: use `#%` instead of #%%`

2. Also about the logic of this command:

If user's selection spans multiple cells - execute each cell (from start till end of each section)  
(note that vscode supports non-continuous selection)

3. Preserve the old `vscode.CheckpointPasteCell`, make this a separate (new) command, for the users who'd prefer the old mechanism


Then I see no problems with it!

**Comment by Splines** [comment]
Where do I find out about `vscode.CheckpointPasteCell` in the [VSCode Extension API](https://code.visualstudio.com/api/references/vscode-api)?

I don't think we have to reinvent the wheel for this. I browsed a bit in the public code of the [`vscode-jupyter`](https://github.com/microsoft/vscode-jupyter) extension, here are some first findings

- An issue called [`Make cells (# %%) collapsible python files`](https://github.com/Microsoft/vscode-jupyter/issues/1527)
- A constant `export const DefaultCodeCellMarker = '# %%';` [here](https://github.com/microsoft/vscode-jupyter/blob/fb42c2069afd743d23a71c2fd340295909dfb58a/src/platform/common/constants.ts#L79)
- A method [**`provideFoldingRanges()`**](https://github.com/microsoft/vscode-jupyter/blob/fb42c2069afd743d23a71c2fd340295909dfb58a/src/interactive-window/editor-integration/pythonCellFoldingProvider.ts#L37-L58) that makes use of VSCode's [`FoldingRangeProvider`](https://code.visualstudio.com/api/references/vscode-api#FoldingRangeProvider)

**Comment by VladimirFokow** [comment]
I think he meant [this](https://github.com/bhoov/vscode-manim/blob/5185acc2dd475a2f0383780eb98c2bf725a5890f/src/extension.ts#L23C55-L23C83) under `vscode.CheckpointPasteCell`

**Comment by Splines** [comment]
> If there is no title for the cell e.g., #%% SECTION TITLE, look in the following line for a normal comment and use this as a section title.

I like the idea of also taking a look in the following line for a normal comment that could provide the title for the cell as well. When the cell is collapsed (folded), we could also use such a comment (if found) and show it in the line that is folded.

> If no section title or comment is present, run checkpoint_paste without the scene checkpointing functionality, raising a warning appropriately

How would a user benefit from just having the `checkpoint_paste()` run  in the terminal and at the same time having a warning issued? Does `checkpoint_paste()` even work without any comments? Maybe just show a warning and do nothing else in this case?

**Comment by bhoov** [comment]
> 1. The fastest solution I see to make it "more usable" is to: use `#%` instead of `#%%`
>    (because `#%` doesn't trigger the jupyter buttons)

But `#%` also doesn't trigger folding regions through the jupyter extension so we would have to define our own custom folding. Indeed, it may be nice to do this to remove dependence on the jupyter extension. I do not think it will be too difficult to do this (i think @Splines figured it was possible in [this comment](https://github.com/bhoov/vscode-manim/issues/1#issuecomment-2420598884), but I haven't had time to look in detail either)

**Comment by Splines** [comment]
I'm happy to contribute the basic cell mechanism by means of #7. This is in construction.
