### ISSUE TITLE
Contribution guidelines

### ISSUE THREAD

**Issue by Splines** [bhoov/vscode-manim#4]
It'd be great to have some contribution guidelines as well as a code of conduct. The contribution guidelines could include some general information on how to proceed, e.g. create an issue beforehand, then work on forked repo, make pull request, make sure new code is linted and tested etc. Also see [this guide](https://opensource.guide/starting-a-project/#writing-your-contributing-guidelines).

With this, it's a lot more convenient for new people to contribute and to manage expectations. And of course, this applies only if you want to accept contributions from the outside, totally understand if you don't, but then maybe note this down somewhere in the Readme or inside a tiny `Contributing.md` file.

**Comment by bhoov** [comment]
Thank you for putting this on my radar. When I whipped this extension up I was definitely in "hacking" mode and did not setup a full OSS dev process. I'm very happy to accept contributions from the outside and to update the Readme/Contributing.md. I will do this when I return from travel next week. Thanks!
